// frontend-react/src/laureate-list/LaureateList.js
import React from 'react';
import './LaureateList.css';

import {DataTable} from 'primereact/datatable';
import {Button} from 'primereact/button';
import {Column} from 'primereact/column';
import {Growl} from 'primereact/growl';

import http from '../http-service/HttpService'

import LaureateDetails from "../laureate-details/LaureateDetails";

class LaureateList extends React.Component {

    getLaureates() {
        http.sendGetRequest('/laureate/getLaureates').then(res => {
            this.setState({laureates: res.data});
        });
    }

    constructor() {
        super();
        this.state = {
            laureates: [],
            laureate: null,
            selectedField: null,
            laureateUpdatable: false
        };

        this.getLaureates();

    }

    actionTemplate(rowData) {
        return (
            <div>
                <Button label="Details" icon="pi pi-search" onClick={this.showDetails.bind(this, rowData)}/>
                <Button label="Update" icon="pi pi-search" onClick={this.showUpdateForm.bind(this, rowData)}/>
                <Button label="Delete" icon="pi pi-search" onClick={this.removeRow.bind(this, rowData)}/>
            </div>);
    }

    showUpdateForm(rowData) {
        this.setState({laureate: rowData, selectedField: rowData.field, laureateUpdatable: true});
    }

    showDetails(rowData) {
        this.setState({laureate: rowData, selectedField: rowData.field, laureateUpdatable: false});
    }

    detailsClosed() {
        this.setState({laureate: null});
    }

    laureateSaved(laureates) {
        debugger;
        this.setState({laureates: laureates, laureate: null});
    }

    removeRow(rowData) {

        http.sendPostRequest('/laureate/delete', {
            id: rowData.id
        }).then(function (response) {
            this.setState({laureates: response.data});
            this.growl.show({
                severity: 'success',
                summary: 'Success Message',
                detail: 'Laureate removed'
            });
        }.bind(this));
    }

    showCreateNewForm() {
        this.setState({laureate: {}, selectedField: null, laureateUpdatable: true});
    }

    render() {

        return (
            <div>
                <Growl ref={(el) => this.growl = el}/>
                <Button label="Add" icon="pi pi-search" onClick={this.showCreateNewForm.bind(this)}/>
                <div className="content-section implementation">
                    <DataTable value={this.state.laureates} paginator={true} rows={10}>
                        <Column field="name" header="Name" filter={true} filterMatchMode="contains"/>
                        <Column field="year" header="Year" filter={true} filterMatchMode="contains"/>
                        <Column field="field.name" header="Field" filter={true} filterMatchMode="contains"/>
                        <Column field="" header="" body={this.actionTemplate.bind(this)}/>
                    </DataTable>
                </div>
                <LaureateDetails laureate={this.state.laureate}
                                 selectedField={this.state.selectedField}
                                 detailsClosed={this.detailsClosed.bind(this)}
                                 laureateSaved={this.laureateSaved.bind(this)}
                                 laureateUpdatable={this.state.laureateUpdatable}
                />
            </div>
        );
    }
}

export default LaureateList;

// frontend/src/app/laureate-list/laureate-list.component.ts
import {Component, OnInit} from '@angular/core';
import {Laureate} from '../model/Laureate';
import {ConfirmationService} from 'primeng/api';
import {LaureateService} from '../services/laureate.service';
import {HttpRequestService} from '../services/http.service';
import {MessageService} from 'primeng/components/common/messageservice';

@Component({
  selector: 'app-laureate-list',
  templateUrl: './laureate-list.component.html',
  styleUrls: ['./laureate-list.component.css']
})
export class LaureateListComponent implements OnInit {

  public laureates: Laureate[] = [];

  public laureate: Laureate = new Laureate;

  display = false;
  updatable = false;

  constructor(private laureateService: LaureateService,
              private httpService: HttpRequestService,
              private confirmationService: ConfirmationService,
              private messageService: MessageService) {
  }

  ngOnInit() {
    this.laureateService.getLaureates().subscribe((laureates: Laureate[]) => {
      this.laureates = laureates;
    });
  }

  showCreateNewForm() {
    this.display = true;
    this.updatable = true;

    this.laureate = new Laureate();
  }

  showDetails(laureate) {
    this.display = true;
    this.updatable = false;

    this.laureate = laureate;
  }

  showUpdateForm(laureate) {
    this.display = true;
    this.updatable = true;

    this.laureate = laureate;
  }

  removeRow(laureate) {
    this.confirmationService.confirm({
      key: 'deleteConfirmation',
      message: null,
      accept: () => {

        const body = {
          'id': laureate.id
        };

        this.httpService.sendPostRequest('/laureate/delete'
          , body, (res: Laureate[]) => {
            this.laureates = res;
            this.laureate = new Laureate;
            this.messageService.add({severity: 'info', summary: 'Laureate removed'});
          }, (res) => {
          });
      }
    });
  }

  laureateSaved(laureates: Laureate[]) {
    this.laureates = laureates;
    this.laureate = new Laureate;
    this.messageService.add({severity: 'info', summary: 'Laureate saved'});
  }

  closeDialog() {
    this.display = false;
    this.updatable = false;
  }

}

<p-confirmDialog key="deleteConfirmation" appendTo="body"
                 acceptLabel="Yes"
                 rejectLabel="No"
                 message="Are you sure you want to delete input?"
                 header=""></p-confirmDialog>

<p-button (onClick)="showCreateNewForm()" label="Add" icon="fa fa-plus"></p-button>
<hr>
<p-dataTable [value]="laureates" [rows]="10" [paginator]="true" [pageLinks]="3" [rowsPerPageOptions]="[5,10,20]">
  <p-column field="name" header="Name" [filter]="true" sortable="true"></p-column>
  <p-column field="year" header="Year" [filter]="true" sortable="true"></p-column>
  <p-column field="field.name" header="Field" [filter]="true" sortable="true"></p-column>
  <p-column field="" header="">
    <ng-template let-laureate="rowData" pTemplate="body">
      <p-button label="Details" (onClick)="showDetails(laureate)"></p-button>
      <p-button icon="fa fa-edit" label="Update" (onClick)="showUpdateForm(laureate)"></p-button>
      <p-button icon="fa fa-trash" label="Delete" (onClick)="removeRow(laureate)"></p-button>
    </ng-template>
  </p-column>
</p-dataTable>
<app-laureate-details [updatable]="updatable" [display]="display" [(laureate)]="laureate"
                      (laureateSaved)="laureateSaved($event)"
                      (closeDialogEvent)="closeDialog()"></app-laureate-details>
