// frontend/src/app/laureate-details/laureate-details.component.ts
import {Component, EventEmitter, Input, OnInit, Output} from '@angular/core';
import {Laureate} from '../model/Laureate';
import {SelectItem} from 'primeng/api';
import {Field} from '../model/Field';
import {LaureateService} from '../services/laureate.service';
import {HttpRequestService} from '../services/http.service';
import {environment} from '../../environments/environment';
import {MessageService} from 'primeng/components/common/messageservice';

@Component({
  selector: 'app-laureate-details',
  templateUrl: './laureate-details.component.html',
  styleUrls: ['./laureate-details.component.css']
})
export class LaureateDetailsComponent implements OnInit {

  @Input()
  display = false;

  @Input()
  updatable = false;

  @Input()
  public laureate: Laureate = new Laureate;

  @Output()
  public closeDialogEvent = new EventEmitter();

  @Output()
  public laureateSaved: EventEmitter<Laureate[]> = new EventEmitter<Laureate[]>();

  public fields: Field[] = [];

  public fieldOptions: SelectItem[] = [];

  public currentYear = new Date().setFullYear(new Date().getFullYear() + 1);

  public firstYear = environment.firstYear;

  constructor(private laureateService: LaureateService,
              private httpService: HttpRequestService) {
  }

  ngOnInit() {
    this.laureateService.getFields().subscribe((fields: Field[]) => {
      this.fields = fields;
      fields.forEach(field => {
        this.fieldOptions.push({
          label: field.name,
          value: field
        });
      });
    });
  }

  saveLaureate(laureate) {

    const body = {
      'id': laureate.id,
      'name': laureate.name,
      'alias': laureate.alias,
      'field': {
        'id': laureate.field.id,
        'name': laureate.field.name
      },
      'year': laureate.year,
      'biography': this.laureate.biography
    };

    this.httpService.sendPostRequest('/laureate/save'
      , body, (res: Laureate[]) => {
        this.closeDialog();
        this.laureateSaved.emit(res);
        this.laureate = new Laureate;
      }, (res) => {
      });
  }

  closeDialog() {
    this.closeDialogEvent.emit();
  }

}

<p-dialog header="Laureate" [visible]="display" (onHide)="closeDialog()" [width]="500">
  <div class="ui-grid">
    <div class="ui-grid-col-12">
      <div class="ui-grid-row">
        <h3 class="first">Name</h3>
      </div>
      <div class="ui-grid-row">
        <input type="text" pInputText [readonly]="!updatable" [disabled]="!updatable" [(ngModel)]="laureate.name">
      </div>
      <div class="ui-grid-row">
        <h3 class="first">Alias</h3>
      </div>
      <div class="ui-grid-row">
        <input type="text" pInputText [readonly]="!updatable" [disabled]="!updatable" [(ngModel)]="laureate.alias">
      </div>
      <div class="ui-grid-row">
        <h3 class="first">Field</h3>
      </div>
      <div class="ui-grid-row">
        <p-dropdown [options]="fieldOptions" [readonly]="!updatable" [disabled]="!updatable"
                    [autoDisplayFirst]="false" [required]="true"
                    [(ngModel)]="laureate.field" [autoWidth]="false"></p-dropdown>
      </div>
      <div class="ui-grid-row">
        <h3 class="first">Year</h3>
      </div>
      <div class="ui-grid-row">
        <input type="text" pInputText [readonly]="true" [disabled]="true" pKeyFilter="int"
               maxlength="4"
               [(ngModel)]="laureate.year">
      </div>
      <div class="ui-grid-row" *ngIf="updatable">
        <p-slider [(ngModel)]="laureate.year" [style]="{'width':'200px'}" [disabled]="false"
                  [min]="firstYear" max="{{currentYear| date:'yyyy'}}"></p-slider>
      </div>
      <div class="ui-grid-row"><h3>Biography</h3></div>
      <div class="ui-grid-row">
        <textarea pInputTextarea [readonly]="!updatable" [disabled]="!updatable"
                  [(ngModel)]="laureate.biography"></textarea>
      </div>
      <div class="ui-grid-row" *ngIf="updatable"><h3></h3></div>
      <div class="ui-grid-row" *ngIf="updatable">
        <p-button label="Save" (onClick)="saveLaureate(laureate)" icon="fa fa-floppy-o"></p-button>
      </div>
    </div>
  </div>
</p-dialog>

// frontend-react/src/laureate-details/LaureateDetails.js
import React from "react";

import {Dialog} from 'primereact/dialog';
import {InputText} from 'primereact/inputtext';
import {InputTextarea} from 'primereact/inputtextarea';
import {Dropdown} from 'primereact/dropdown';
import {Button} from 'primereact/button';

import http from '../http-service/HttpService'

class LaureateDetails extends React.Component {

    constructor(props) {
        super(props);
        this.state = {
            fieldOptions: [],
            selectedLaureate: null,
            selectedField: props.laureate !== null ? props.laureate.field : null
        };

        this.getFields();

    }

    getFields() {
        http.sendGetRequest('/laureate/getFields').then(res => {
            const fieldOptions = [];
            res.data.forEach(el => {
                fieldOptions.push({label: el.name, value: el});
            });
            this.setState({fieldOptions: fieldOptions});
        });
    }

    closeDetails() {
        this.setState({selectedField: null, selectedLaureate: null});
        this.props.detailsClosed();
    };

    saveLaureate() {
        const laureate = (this.state.selectedLaureate !== null) ? this.state.selectedLaureate : this.props.laureate;
        laureate.field = (this.state.selectedField !== null) ? this.state.selectedField : this.props.selectedField;

        http.sendPostRequest('/laureate/save', laureate).then(function (response) {
            this.setState({selectedField: null, selectedLaureate: null});
            this.props.laureateSaved(response.data);
        }.bind(this));
    }

    fieldDropdown(laureateUpdatable) {
        if (laureateUpdatable) {
            return (<div className="p-col-12">
                <Dropdown
                    value={(this.state.selectedField !== null) ? this.state.selectedField : this.props.selectedField}
                    options={this.state.fieldOptions}
                    disabled={!this.props.laureateUpdatable}
                    onChange={(e) => {
                        this.setState({selectedField: e.value});
                    }}/>

            </div>);
        }
        return (
            <div className="p-col-12">
                <InputText value={this.props.selectedField.name}
                           disabled={true}
                           style={{width: '100%'}}/>
            </div>
        );
    }

    render() {

        if (this.props.laureate !== null) {
            return (
                <Dialog header="Laureate" visible={this.props.laureate !== null}
                        width="500px" modal={true} onHide={this.closeDetails.bind(this)}>
                    <div className="p-grid">
                        <div className="p-col-12">
                            <h3 className="first">Name</h3>
                        </div>
                        <div className="p-col-12">
                            <InputText
                                value={(this.state.selectedLaureate !== null) ? this.state.selectedLaureate.name : this.props.laureate.name}
                                disabled={!this.props.laureateUpdatable}
                                onChange={
                                    (e) => {
                                        let selectedLaureate = (this.state.selectedLaureate !== null) ? this.state.selectedLaureate : this.props.laureate;
                                        selectedLaureate = {...selectedLaureate};
                                        selectedLaureate.name = e.target.value;
                                        this.setState({selectedLaureate: selectedLaureate});
                                    }
                                }
                                style={{width: '100%'}}/>
                        </div>
                        <div className="p-col-12">
                            <h3 className="first">Alias</h3>
                        </div>
                        <div className="p-col-12">
                            <InputText
                                value={(this.state.selectedLaureate !== null) ? this.state.selectedLaureate.alias : this.props.laureate.alias}
                                onChange={
                                    (e) => {
                                        let selectedLaureate = (this.state.selectedLaureate !== null) ? this.state.selectedLaureate : this.props.laureate;
                                        selectedLaureate = {...selectedLaureate};
                                        selectedLaureate.alias = e.target.value;
                                        this.setState({selectedLaureate: selectedLaureate});
                                    }
                                }
                                disabled={!this.props.laureateUpdatable} style={{width: '100%'}}/>
                        </div>
                        <div className="p-col-12">
                            <h3 className="first">Field</h3>
                        </div>

                        {this.fieldDropdown(this.props.laureateUpdatable, this.props.laureate.field)}

                        <div className="p-col-12">
                            <h3 className="first">Year</h3>
                        </div>
                        <div className="p-col-12">
                            <InputText
                                value={(this.state.selectedLaureate !== null) ? this.state.selectedLaureate.year : this.props.laureate.year}
                                onChange={
                                    (e) => {
                                        let selectedLaureate = (this.state.selectedLaureate !== null) ? this.state.selectedLaureate : this.props.laureate;
                                        selectedLaureate = {...selectedLaureate};
                                        selectedLaureate.year = e.target.value;
                                        this.setState({selectedLaureate: selectedLaureate});
                                    }
                                }
                                disabled={!this.props.laureateUpdatable} style={{width: '100%'}}/>
                        </div>
                        <div className="p-col-12">
                            <h3 className="first">Biography</h3>
                        </div>
                        <div className="p-col-12">
                            <InputTextarea rows={5} cols={30}
                                           value={(this.state.selectedLaureate !== null) ? this.state.selectedLaureate.biography : this.props.laureate.biography}
                                           onChange={
                                               (e) => {
                                                   let selectedLaureate = (this.state.selectedLaureate !== null) ? this.state.selectedLaureate : this.props.laureate;
                                                   selectedLaureate = {...selectedLaureate};
                                                   selectedLaureate.biography = e.target.value;
                                                   this.setState({selectedLaureate: selectedLaureate});
                                               }
                                           }
                                           disabled={!this.props.laureateUpdatable}/>
                        </div>
                        <div className="p-col-12" style={{display: this.props.laureateUpdatable ? '' : 'none'}}>
                            <Button label="Save" onClick={this.saveLaureate.bind(this)}/>
                        </div>
                    </div>
                </Dialog>
            );
        }
        return (<div></div>);

    }

}

export default LaureateDetails;
